[book]
authors = ["VirtualTam"]
language = "en"
multilingual = false
src = "src"
title = "SparkleMuffin: Documentation"

[build]
create-missing = false

[output.html]
additional-css = ["theme/css/custom.css"]

[output.linkcheck]
# https://github.com/Michael-F-Bryan/mdbook-linkcheck

# Disabled by default, use to check links to external websites.
# Remote servers may respond to HEAD requests with an HTTP 405 Method Not Allowed error status.
#follow-web-links = true
#exclude = ['localhost']
